id = "kira"
name = "Kira"
version = "0.1.0"
schema_version = 1
authors = ["Kira"]
description = "Syntax highlighting support for Kira."
repository = "https://github.com/kira-lang-com/kira-zed-extension"
languages = ["languages/kira"]
themes = []
icon_themes = []
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.kira]
repository = "https://github.com/kira-lang-com/kira-tree-sitter"
rev = "9c7db31a7ace8469a691e75d32a1c2ee79da3505"
