name = "Kira"
grammar = "kira"
path_suffixes = ["kira"]
line_comments = ["// "]
autoclose_before = ";:.,=}])> \n\t"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
]
tab_size = 4
